services:
  insomniapp-web:
    image: insomniapp-web
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    container_name: insomniapp-web
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - ea-ingress
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      kuma.insomniapp.group.name: "insomniapp"
      kuma.insomniapp-web.http.name: "website"
      kuma.insomniapp-web.http.parent_name: "insomniapp"
      kuma.insomniapp-web.http.url: "https://insomnia.atbas.xyz"

networks:
  ea-ingress:
    external: true
